### ISSUE TITLE
RSS titles

### ISSUE THREAD

**Issue by topper-123** [ludicrousxyz/tab#31]
Id would be nice if the RSS feeds would show titles or letting users set RSS titles.

**Comment by nahtnam** [comment]
Hey, great idea. Currently I'm fighting with Google to keep my extension on the store but I can add this after. I'll also make sure to add it to the 2.0 version I am working on which is much better looking

**Comment by topper-123** [comment]
Nice, thanks. I'm looking forward to see what you come up with.

**Comment by nahtnam** [comment]
Hey sorry for the late reply. We have added this to our roadmap for the v2 release and it will be for sure included! I'm trying to get the BETA out as soon as possible, and ill update the old chrome extension with more details as I get closer
